//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyKeeper.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKOptionPlayer
    {
        public int Id { get; set; }
        public int TournamentPlayerId { get; set; }
        public int OptionId { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
    
        public virtual TKOption TKOption { get; set; }
        public virtual TKTournamentPlayer TKTournamentPlayer { get; set; }
    }
}
