//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyKeeper.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKOrganizer
    {
        public int PlayerId { get; set; }
        public int TournamentId { get; set; }
        public int Id { get; set; }
    
        public virtual TKPlayer TKPlayer { get; set; }
        public virtual TKTournament TKTournament { get; set; }
    }
}
