//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyKeeper.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKRanking
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public double Points { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string PlayerName { get; set; }
        public int RankingTypeId { get; set; }
        public Nullable<System.DateTime> LatestGame { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual TKPlayer TKPlayer { get; set; }
        public virtual TKRankingType TKRankingType { get; set; }
    }
}
