//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyKeeper.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKTournamentPlayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TKTournamentPlayer()
        {
            this.TKGame = new HashSet<TKGame>();
            this.TKGame1 = new HashSet<TKGame>();
            this.TKOptionPlayer = new HashSet<TKOptionPlayer>();
        }
    
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int TournamentId { get; set; }
        public int Seed { get; set; }
        public bool Paid { get; set; }
        public string CustomPlayerNumber { get; set; }
        public int FairPlay { get; set; }
        public int Painting { get; set; }
        public int Penalty { get; set; }
        public Nullable<int> TournamentTeamId { get; set; }
        public Nullable<int> PrimaryCodexId { get; set; }
        public Nullable<int> SecondaryCodexId { get; set; }
        public Nullable<int> TertiaryCodexId { get; set; }
        public string ArmyList { get; set; }
        public bool DoNotRank { get; set; }
        public int BattlePoints { get; set; }
        public int SecondaryPoints { get; set; }
        public string Club { get; set; }
        public int Quiz { get; set; }
        public string PlayerName { get; set; }
        public string GamePath { get; set; }
        public int Wins { get; set; }
        public int Draws { get; set; }
        public int Losses { get; set; }
        public Nullable<int> TournamentPoints { get; set; }
        public bool NonPlayer { get; set; }
        public bool Active { get; set; }
        public Nullable<int> QuaternaryCodexId { get; set; }
        public string PaymentToken { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual TKCodex TKCodex { get; set; }
        public virtual TKCodex TKCodex1 { get; set; }
        public virtual TKCodex TKCodex2 { get; set; }
        public virtual TKCodex TKCodex3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKGame> TKGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKGame> TKGame1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKOptionPlayer> TKOptionPlayer { get; set; }
        public virtual TKPlayer TKPlayer { get; set; }
        public virtual TKTournament TKTournament { get; set; }
        public virtual TKTournamentTeam TKTournamentTeam { get; set; }
    }
}
