//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyKeeper.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKTournamentTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TKTournamentTeam()
        {
            this.TKTeamMatch = new HashSet<TKTeamMatch>();
            this.TKTeamMatch1 = new HashSet<TKTeamMatch>();
            this.TKOptionTeam = new HashSet<TKOptionTeam>();
            this.TKTournamentPlayer = new HashSet<TKTournamentPlayer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TournamentId { get; set; }
        public int Penalty { get; set; }
        public int BattlePoints { get; set; }
        public int MatchPoints { get; set; }
        public int SecondaryPoints { get; set; }
        public int BattlePointPenalty { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string PaymentToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKTeamMatch> TKTeamMatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKTeamMatch> TKTeamMatch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKOptionTeam> TKOptionTeam { get; set; }
        public virtual TKTournament TKTournament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKTournamentPlayer> TKTournamentPlayer { get; set; }
    }
}
