//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyKeeper.Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourneyKeeperEntities : DbContext
    {
        public TourneyKeeperEntities()
            : base("name=TourneyKeeperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TKCodex> TKCodex { get; set; }
        public virtual DbSet<TKFrontPageLinks> TKFrontPageLinks { get; set; }
        public virtual DbSet<TKGame> TKGame { get; set; }
        public virtual DbSet<TKGameSystem> TKGameSystem { get; set; }
        public virtual DbSet<TKOrganizer> TKOrganizer { get; set; }
        public virtual DbSet<TKPlayer> TKPlayer { get; set; }
        public virtual DbSet<TKRanking> TKRanking { get; set; }
        public virtual DbSet<TKRankingType> TKRankingType { get; set; }
        public virtual DbSet<TKSinglesScoringSystem> TKSinglesScoringSystem { get; set; }
        public virtual DbSet<TKTeamMatch> TKTeamMatch { get; set; }
        public virtual DbSet<TKTeamScoringSystem> TKTeamScoringSystem { get; set; }
        public virtual DbSet<TKTournamentTeam> TKTournamentTeam { get; set; }
        public virtual DbSet<TKTournamentType> TKTournamentType { get; set; }
        public virtual DbSet<TKOption> TKOption { get; set; }
        public virtual DbSet<TKOptionTeam> TKOptionTeam { get; set; }
        public virtual DbSet<TKOptionPlayer> TKOptionPlayer { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<TKTournament> TKTournament { get; set; }
        public virtual DbSet<TKTournamentPlayer> TKTournamentPlayer { get; set; }
    }
}
